### ISSUE TITLE
Create Highlighted votes component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#1]
Create the highlighted votes component which should have the Poll name (question), the category of the poll, and it should also include the amount of votes and comments that the poll has. The component should receive the following parameters: 
- question
- category
- votes
- comments 

Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="500" alt="Screenshot 2024-12-12 at 01 08 28" src="https://github.com/user-attachments/assets/b45ea608-1492-479e-9bab-e10de4e04255" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by System625** [comment]
Hello
I would love to work on this
I will draft a PR 12 hours into the work
My ETA is 24 hours

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by NueloSE** [comment]
May I take care of this?

**Comment by Supa-mega** [comment]
Can I tackle this one?

**Comment by Adedayo-Data** [comment]
Could I be assigned to this?
Hi, I've reviewed the project and I'm confident I can create the highlighted votes component. The component will display the poll name, category, votes, and comments, using the required parameters: question, category, votes, and comments. I'll ensure the design aligns with the provided color palette. Let me know how to proceed!

**Comment by derianrddev** [comment]
**Hello SocialSphere team,**

I’m **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your Stellar-based project during the **Only Dust 11** hackathon 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to resolve the *issue*

1. Build a functional React component named `HighlightedVotesComponent`.
2. Configure the component to accept `question`, `category`, `votes`, and `comments` as parameters.
3. Design the component strictly following the provided color palette and reference image.
4. Ensure responsiveness and deliver a user-friendly interface consistent with the platform’s overall design.
5. Validate the functionality and accessibility of the component (e.g., screen reader support).

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by kayceeDev** [comment]
Can I try solving this issue?

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by chigozzdevv** [comment]
May I handle this issue?

**Comment by mimisavage** [comment]
May I pick this up?

**Comment by Pvsaint** [comment]
Can I take this from here? I'm a Frontend and smart contract developer

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by DuendexCR** [comment]
Can I tackle this one?

**Comment by fabrobles92** [comment]
Hello I am Fab, a member of dojo coding and also a full stack engineer with experience in Next Js, Vue and plain react, also I have plenty of contribution to web3 projects where that experience can help me deliver a quality solution

How plan to tackle this:
Create a component with the colors provided in the issue description with its input params
Use tailwind or similar 
Test it in different screens

**Comment by FrankiePower** [comment]
Can I tackle this one?

**Comment by FrankiePower** [comment]
I am a frontend developer with over 3 years of experience, and I have recently graduated from Web3Bridge Africa, the premier and largest blockchain developer community in Africa. I am well-equipped to build the highlighted votes component with a focus on both functionality, responsiveness and accessibility.This project will take me approximately one day to complete,.
ETA: 1 DAY

**Comment by Dorcas18** [comment]
May I handle this issue?

**Comment by sandragcarrillo** [comment]
Would love to contribute to this project, I'm a fan of the DAO space and love that you are building this. I have created similar smaller projects for Hackathons so I'm kind of familiar with this type of components. 

I have experience as frontend developer and blockchain developer, so I believe I could solve this issue, I would take the Figma component design as the guide to create it using the color pallette.

**Comment by Nityam573** [comment]
Is it okay if I take this?
