### ISSUE TITLE
Create Navbar - Landing Page component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#10]
Create the Navbar - Landing Page component it should have the logo, About Us, Services, Use Cases, Forum and a button to launch Dapp. The component should NOT receive anything since it is static. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="674" alt="Screenshot 2024-12-12 at 01 28 12" src="https://github.com/user-attachments/assets/e459c5ea-1ae5-49e8-be85-8ef4ab482074" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by Kingsuite** [comment]
I’d like to resolve this.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects)

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by kayceeDev** [comment]
May I be assigned to this?

**Comment by austineblaise** [comment]
I'm a frontend JavaScript/TypeScript Blockchain developer. I'll create the Navbar for the landing page, including the logo, About Us, Services, Use Cases, Forum, and a button to launch the Dapp. The component will be static and not receive any props. I'll ensure it follows the color palette for accurate colors. Excited to get this done!

**Comment by SimplementeCao** [comment]
Create the Navbar component it should have the Navbar Item component, the Navbar Profile Component and the logo. The component should NOT receive anything since it is static. Please refer to the color palette for the accurate hex code colors.

Component Image:

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
Mind if I try this one?

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies. My expertise includes: Nuxt.js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. I would love to contribute to this project.
I would love to contribute to this project. My approach towards this issue after forking the repo and creating the branch would be to first define the colours according to the colours in the GitHub. I would then import the logo, create a list items for the links and also a button for the launch drop. I would then style it with tailwind css to fit the look of how its meant to be like the design

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi (@deeseeker), a frontend developer with over two years of experience in React, TypeScript, and JavaScript. I am currently working on a social media app for African creators (https://app.myrevva.com/).

I have reviewed the requirements carefully and will create the navbar component with all the items-about us,services, use cases, forum and button to launch the Dapp with great attention to detail. You can check out my portfolio for a sample of my work, such as https://logisfi-pro-app.vercel.app/, available on my GitHub.

I would love the opportunity to take on this issue.

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by Kaminar-i** [comment]
Can I resolve this issue.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by SimplementeCao** [comment]
Hi, I'm Leandro, Front-end developer.
I would solve the issue first by reviewing the image design and adjusting to the component-based development guideline to maintain consistency and scalability of the project.
Estimated delivery time: 20 hours.

I have contributed before to other projects like:
- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

**Comment by sebas11042** [comment]
Background:
I’m a software developer with experience in Java, JavaScript, React, and C#. I’m also part of the Dojo Coding community and a member of the Sunset Labs team, where we are developing an on-chain game. My skills span both backend and frontend technologies, and I’m passionate about building innovative, decentralized applications. As part of the Sunset Labs team, I am actively contributing to the development of our blockchain-based game, combining my expertise in software development with my interest in cutting-edge technologies.

Solution:
To implement the static navigation bar component, I will use the specified file and create a structure that includes the logo, links such as "About Us," "Services," "Use Cases," "Forum," and a prominent "Launch Dapp" button. I will strictly follow the provided color palette (#EEEEEE for the background, #E36C59 for the button, and secondary colors like #4ECCA3) and ensure a responsive design using Tailwind CSS or custom classes. The navigation bar will be visually consistent with the Figma design to ensure a modern and professional appearance.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Luluameh** [comment]
Let me handle this issue!

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue

**Comment by portableDD** [comment]
Hi, I am Emmanuel Dorcas, a software develper with React js and Typescript , i will like to tackle this issues, my estimated day is 1 day.

how will I tackle this issue:
I will be creating an array for the nav list, and mapping through it to create the list item in the ul.
I will be using tailwind CSS for styling.

thanks

**Comment by caxtonacollins** [comment]
Can I take this from here?

**Comment by Emmanex01** [comment]
Can I start working on this?

**Comment by respp** [comment]
Can I take this from here?

**Comment by khayss** [comment]
I'm a full-stack developer. I have the ability to build responsive and user-friendly UIs for production grade applications.

I understand what is required to complete this issue. I'll:
- Create the NavBar component containing all the required details.
- Design and Style it to integrate perfectly with the landing page.
- Integrate it with the landing page.
- This component is static and does not have any props according to the requirement.
- Ensure this fits in well with the overall app UI without breaking the UI.

I'm excited about working on this.

**Comment by pheobeayo** [comment]
Can I handle this task?

**Comment by Dorcas18** [comment]
Can I attempt this issue?

**Comment by ekumamatthew** [comment]
Can I try solving this issue?

**Comment by Prosper1218** [comment]
can i work on this ?
i'll make my first PR in in 30hrs
