### ISSUE TITLE
Create Navbar - Dapp component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#11]
Create the Navbar component it should have the Navbar Item component, the Navbar Profile Component and the logo. The component should NOT receive anything since it is static. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="256" alt="Screenshot 2024-12-12 at 01 30 05" src="https://github.com/user-attachments/assets/e5e92292-3a97-41c2-85b6-8c0a8219bc98" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

For this component use the example from https://ui.shadcn.com/docs/components/sidebar

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects)

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by Supa-mega** [comment]
I'd like to handle this task.

**Comment by NueloSE** [comment]
Could I try solving this?

**Comment by Kingsuite** [comment]
I’d like to resolve this.

**Comment by 3th-Enjay** [comment]
Would love to tackle this!

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe
• Scaffold-ETH
• BuidlGuidl

I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.

Can I work on this issue?

Plan to Solve the Issue:

Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by kayceeDev** [comment]
Can I jump on this task?

**Comment by jahrulezfrancis** [comment]
For the navbar component, I’ll create it to include the navbar item component, the navbar profile component, and the logo. Since it’s static, the component won’t need to receive any props. I’ll also make sure to use the correct hex code colors from the color palette you provided. I can have it done within 24 hours.

**Comment by SimplementeCao** [comment]
Create the Navbar component it should have the Navbar Item component, the Navbar Profile Component and the logo. The component should NOT receive anything since it is static. Please refer to the color palette for the accurate hex code colors.

Component Image:

**Comment by Adedayo-Data** [comment]
Hi, I'm interested in taking on the this task. I've reviewed the requirements and I'm confident I can deliver. I'd love to discuss further and get started. Looking forward to hearing from you.

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by anonfedora** [comment]
I'm fullstck blockchain developer, proficient in Reactjs, Cairo, Rust, Nextjs, Nestjs

Will check the figma design if available to implement the Navbar component as required following best practices.

**Comment by derianrddev** [comment]
**Hello SocialSphere team,**

I’m **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your Stellar-based project during the **Only Dust 11** hackathon 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to resolve the *issue*

1. Design a static React component that includes:
    - The **Navbar Item** component.
    - The **Navbar Profile** component.
    - The page logo.
2. Ensure the component does not receive any parameters as it is static.
3. Use the provided color palette to ensure visual consistency.
4. Validate the final design using the reference image.
5. Test the component to ensure all elements are functional and visually appealing.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by therealemino** [comment]
Could I take a shot at this?

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by No-bodyq** [comment]
Would love to tackle this!

**Comment by SimplementeCao** [comment]
Hi, I'm Leandro, Front-end developer.
I would solve the issue first by reviewing the image design and adjusting to the component-based development guideline to maintain consistency and scalability of the project.
Estimated delivery time: 20 hours.

I have contributed before to other projects like:

Cairo Book
Starknet Book
Starknet Docs
Starknet Security Challenges Factory
Starkane
Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: OnlyDust Profile,
and my GitHub

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue

**Comment by caxtonacollins** [comment]
Can I work on this, please?

**Comment by Emmanex01** [comment]
I'm Emmanuel Tochukwu, 
A Frontend developer, proficient in Reactjs, tailwindcss, typescript, Cairo Programming Languages.
I'd like to handle this task?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Shalomnze** [comment]
Hi, I am Nze Shalom, I’ve over 2 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS) and currently learning cairo. I've gone through the repository and design. I believe this is an excellent first issue for me to contribute to. Can take on this task? ETA is 6hrs

**Comment by DioChuks** [comment]
Could I take over this issue?

**Comment by Dorcas18** [comment]
Could I take over this issue?

**Comment by Nityam573** [comment]
May I try my hand at this?
Plan to Solve the Issue:

Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by bitfalt** [comment]
Closed by #17
