### ISSUE TITLE
Create Community Banner component

### ISSUE THREAD

**Issue by LazarusAA** [ZencypherSolutions/socialsphere#15]
Create the Community Banner component it should have an “icon” like shape, the name of the community, a button saying More info, and the amount of members. The component should receive the name of the community, the “icon” like shape, the functionality of the more info button, and the number of members. Please refer to the color palette for the accurate hex code colors.

Component Image:
![image](https://github.com/user-attachments/assets/2ab2c183-3f16-4030-a251-20270faa2160)

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by 0xdevcollins** [comment]
Can I attempt this issue?

I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Kachimercy1** [comment]
I’d like to help with this.

**Comment by Supa-mega** [comment]
Let me handle this issue!

**Comment by 3th-Enjay** [comment]
Could I try solving this?

**Comment by jahrulezfrancis** [comment]
For the Community Banner component, I’ll create an "icon"-like shape, display the community's name, and include a "More Info" button with the necessary functionality. I’ll also show the number of members in the community. The component will receive the community name, the "icon"-like shape, the functionality for the "More Info" button, and the number of members as props. I’ll make sure to use the accurate hex code colors from the color palette as well. I can have this ready within 24 to 36 hours

**Comment by Adedayo-Data** [comment]
Hi, I'm interested in taking on the this task. I've reviewed the requirements and I'm confident I can deliver. I'd love to discuss further and get started. Looking forward to hearing from you.

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #11! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will create the Community Banner component, which will include an “icon” like shape, the community name, a "More info" button, and the number of members. The component will receive the community name, the “icon” like shape, the functionality of the "More info" button, and the number of members, following the content provided.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by akintewe** [comment]
Hi, I'm interested in taking on the this task. I am a frontend/ UIUX developer and i have experience in working with detailed designs. I've reviewed the requirements and I'm confident I can deliver. I'd love to discuss further and get started. Looking forward to hearing from you. ETA 8hours :)

**Comment by 1nonlypiece** [comment]
Hi , I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.

ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Amizeey** [comment]
Can I work on this, please?

**Comment by Shukazuby** [comment]
I am Zubaidat, a frontend developer experienced in building responsive and user-friendly components.

Approach:

I will create the Community Banner component to display an icon-like shape, the community name, a "More Info" button, and the member count. The component will accept props for the community name, icon, a click handler for the "More Info" button, and the number of members. It will be designed to adhere to the provided color palette using accurate hex codes and will be responsive for different screen sizes. The component will be reusable and maintainable, with proper styling and functionality integration for the button. I estimate completing the task in 2-3 days.

ETA:
24-48hrs

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by emarc99** [comment]
I am a member of the Web3Bridge coding community, and I have built similar pages recently: https://github.com/emarc99/no-fail.
With my UI/UX and frontend development (React Vite, Tailwind, NextJs) experience, I will create pitch-perfect design and ensure functionality meet the requirement. I will also test and build.

**Comment by Agbeleshe** [comment]
Hello, I am a frontend developer with over three years working experience. I would love to be assigned this issue. I will create a reusable `CommunityBanner` component that takes the following props: `name` (community name), `icon` (an icon-like shape), `moreInfoHandler` (functionality for the "More Info" button), and `members` (number of community members). The component will be styled to match the provided color palette using accurate hex code colors. It will include:  
- A visually appealing icon placeholder or image.  
- The community name displayed prominently.  
- A "More Info" button with the passed functionality.  
- A styled display of the member count.  

The component will be tested for responsiveness and accessibility, ensuring it fits seamlessly within the application's design system.

My estimated time to complete this task is 1–3 hours.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
I have solid experience in both web2 and web3 and have contributed to open-source projects that ended up being merged both on web2 and web3
will be glad to work on this as my first contribution to this project

**Comment by respp** [comment]
Hello, I am Renzo: [www.renzobarcos.site](http://www.renzobarcos.site)  
I feel that I can add value to applications focused on component design. I am part of the Dojo community and am excited about the opportunity to make my first contributions to SocialSphere.  

In addition to my experience as a frontend and full-stack developer, I have a strong understanding of UI/UX principles, which will allow me to design and implement the community banner component following the necessary requirements.

Thank you for the opportunity 🚀!

**Comment by Emmanex01** [comment]
Can I work on this, please?

**Comment by caxtonacollins** [comment]
Can I jump on this task?

**Comment by josephpdf** [comment]
Hi @LazarusAA 
I'm Joseph Poveda, a member of the Dojo Coding community, I have experience in different programming languages ​​and have contributed to different OSS projects.
To solve the issue I propose
1. **Component Structure**:
   - Create a reusable `CommunityBanner`
   - Define props for `name`, `icon`, `members`, and `onMoreInfoClick` for flexibility.
2. **Design Implementation**:
   - Use the project's specified color palette for accurate styling.
   - Include an icon placeholder, name text, "More Info" button, and member count.
3. **Styling**:
   - Utilize CSS or a styling library for a clean, responsive layout.
   - Ensure the design aligns with the project's aesthetic.
4. **Testing**:
   - Validate functionality for all props and responsiveness across devices.
5. **Code Submission**:
   - Test thoroughly, commit changes, and open a pull request for review.

**Comment by khayss** [comment]
I'm a fullstack developer with good experience in building frontend with frameworks like ReactJS. I love paying attention to details. I build responsive and fleunt UIs.

For this Issue:
- I will create a component for the `Community Banner` following the project structure.
- Style and design this component to meet the requirement of this issue.
- Integrate the component in the right section.

I'll love to handle this issue and give the best and detailed result.

**Comment by DuendexCR** [comment]
May I try my hand at this?

**Comment by drakkomaximo** [comment]
## Solution to Create Community Banner Component

Hi, I’m part of the Dojo Coding team, and I’m ready to help with your project.

To solve the task of creating the **Community Banner component**, here’s what I would do:

1. **Create the Component**:
   - The component should receive:
     - `communityName`: Name of the community
     - `icon`: A shape or icon representing the community
     - `moreInfoButtonHandler`: A function for the "More info" button
     - `numberOfMembers`: Number of members in the community

2. **Design & Styling**:
   - Use a simple design with a rounded container and a circular icon.
   - The "More info" button should be styled clearly, and the colors should match the project's palette.

3. **Functionality**:
   - When the "More info" button is clicked, it should trigger the `moreInfoButtonHandler` function (e.g., open a modal or navigate to a page).

4. **Next Steps**:
   - Build the component using the props provided and ensure it's consistent with the project's design system.
   - Test it to make sure the button works and displays the community info correctly.

Let me know if you need further details!

**Comment by NueloSE** [comment]
Mind if I try this one?

**Comment by AdejareSamad** [comment]
@LazarusAA I can work on this.

**Comment by PeterOche** [comment]
Could I grab this task?

**Comment by BoltUltra** [comment]
I like cherry
Can i be assigned the task.

Telegram Handle: @Dami1o1a

**Comment by davedumto** [comment]
Hi,
My name is David, and I’m a first-time contributor. I’m a frontend developer skilled in JavaScript, TypeScript, TailwindCSS, and ShadCN. I can create the Community Banner component as specified, ensuring it’s modular, responsive, and aligned with the color palette.
ETA 1day

**Comment by Dorcas18** [comment]
can i be trusted with this issue

**Comment by Nityam573** [comment]
I'd like to take this issue.
I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions
I will create the Community Banner component, which will include an “icon” like shape, the community name, a "More info" button, and the number of members. The component will receive the community name, the “icon” like shape, the functionality of the "More info" button, and the number of members, following the content provided.

**Comment by Prosper1218** [comment]
May i cook this for you ?
I'm prosper Williams, a frontend/Blockchain developer. Proficient in utilizing Js/Ts and their frameworks {Nextjs / React}.
i would love to contribute to this project.
thanks

**Comment by bitfalt** [comment]
Closed by #21
