### ISSUE TITLE
Create Highlighted votes carrousel

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#2]
Use the highlighted votes component to create a carousel from multiple highlighted votes components.

Component image:
<img width="645" alt="Screenshot 2024-12-12 at 01 14 50" src="https://github.com/user-attachments/assets/417f4010-e2e8-4a40-98d1-06cc67d9750b" />

**Comment by System625** [comment]
Hello
I would love to work on this
I will draft a PR 12 hours into the work
My ETA is 24 hours

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by CollinsC1O** [comment]
Could I grab this task?

**Comment by Kingsuite** [comment]
Can I tackle this one?

**Comment by Supa-mega** [comment]
Can I start working on this?

**Comment by NueloSE** [comment]
Could I try solving this?

**Comment by kayceeDev** [comment]
I’d like to help with this.

**Comment by derianrddev** [comment]
**Hello SocialSphere team,**

I’m **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your Stellar-based project during the **Only Dust 11** hackathon 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to resolve the *issue*

1. Develop a functional container in React to implement the carousel.
2. Configure the carousel to render multiple instances of the `HighlightedVotesComponent`.
3. Add navigation functionality to the carousel, with arrows and/or auto-scroll features.
4. Ensure the carousel is responsive and adapts to different screen sizes.
5. Validate the functionality and accessibility of the carousel (e.g., keyboard and screen reader support).

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by jahrulezfrancis** [comment]
I would love to work on this. To create the carousel from multiple highlighted votes components, I’ll use the existing highlighted votes component and set up the carousel functionality around it. I’ll make sure it displays multiple instances of the component in a carousel layout. I can have it shipped in 24 to 36 hours.

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will create a carousel from multiple highlighted votes components using the highlighted votes component, following the content provided.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
I'd like to handle this task.

**Comment by josephchimebuka** [comment]
Hello @lukaspetrasek I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchttps://mattedsgn.com/himebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/  I'd be happy to do this

**Comment by mimisavage** [comment]
May I be assigned to this?

**Comment by Pvsaint** [comment]
Can I take care of this issue? I'm Victor,  a front-end and smart contract developer, with 3 years experience in react js.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue and my ETA is 12-16 hours

**Comment by caxtonacollins** [comment]
Can I handle this task?

**Comment by DuendexCR** [comment]
Is this issue still available?

**Comment by therealemino** [comment]
I’m interested in this one.

**Comment by FrankiePower** [comment]
My name is Franklin Ejezie aka Super Franky, i am a frontend developer with 3 years experience and recently graduated from web3bridge africa, the premier and biggest blockhain developer community in africa. i am well equipped to build out the highlighted votes carousel. 
ETA is 1 day.

**Comment by Dorcas18** [comment]
I'd like to handle this task.

**Comment by sandragcarrillo** [comment]
Would love to contribute to this project, I'm a fan of the DAO space and love that you are building this. I have created similar smaller projects for Hackathons so I'm kind of familiar with this type of components. 

I have experience as frontend developer and blockchain developer, so I believe I could solve this issue, I would take the Figma component design as the guide to create it using the color pallette.

**Comment by Nityam573** [comment]
Mind if I try this one?

**Comment by sandragcarrillo** [comment]
Thanks @bitfalt. I'll wait until the PR with the highlighted vote component is merged in the project to make this component and submit my PR

**Comment by evgongora** [comment]
Hey @sandragcarrillo were almost merging the component so you can start with yours, thank you so much for your patience 🙏🏻
