### ISSUE TITLE
Create CommunityCard component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#5]
Create the Community Card component which should have the community name, amount of members, category, and when it was created (Created: xx days ago). The component should receive the following parameters: community name, amount of members, category, amount of days since it has been created. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="712" alt="Screenshot 2024-12-12 at 01 20 40" src="https://github.com/user-attachments/assets/3fb3e64f-b8a7-4ca8-8e30-b0fa757545c2" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects)

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by 3th-Enjay** [comment]
Could I grab this task?

**Comment by kayceeDev** [comment]
May I pick this up?

**Comment by chigozzdevv** [comment]
I’m interested in this one.

**Comment by mimisavage** [comment]
I'd like to handle this task.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue and my ETA is 8 hours

**Comment by Belloabraham121** [comment]
Hi, I'm Iteooluwakisi!

I am a member of Web3Bridge and an experienced frontend developer proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.
I have previously contributed to several projects, including:

CoinSafe: A DeFi startup built on Lisk.
Scaffold-ETH: A popular development framework for Ethereum.
BuidlGuidl: A community-focused platform for Ethereum builders.
I’m confident in my ability to tackle this issue and contribute effectively to the project.

Plan to Solve the Issue:

Familiarize with the Codebase

Review the existing structure and functionality of the codebase.
Identify key components and dependencies relevant to the issue.
Understand the Problem

Carefully analyze the issue details to clarify the requirements.
Explore any linked resources or documentation to gain a comprehensive understanding.
Implement the Solution

Develop a solution leveraging my technical skills and experience.
Test thoroughly to ensure functionality and resolve edge cases.
Collaborate and Communicate

Reach out to the relevant group/chat for clarifications if needed.
Engage proactively to avoid delays and ensure alignment with project goals.
Submit and Refine

Open a Pull Request (PR) with detailed descriptions and documentation.
Address feedback promptly and make any necessary adjustments.
Looking forward to contributing and learning!

**Comment by Dorcas18** [comment]
May I take care of this?
