### ISSUE TITLE
Create Post component

### ISSUE THREAD

**Issue by bitfalt** [ZencypherSolutions/socialsphere#7]
Create the Post component which should have the Post Profile component, the question, the category and the amount of votes. The component should receive the following parameters: question, category, and amount of votes. Please refer to the color palette for the accurate hex code colors.

Component Image:
<img width="660" alt="Screenshot 2024-12-12 at 01 23 19" src="https://github.com/user-attachments/assets/5658aa6e-6b45-4297-81a6-2f55c61a3cbe" />

Color Palette:
<img width="739" alt="Color Palette" src="https://github.com/user-attachments/assets/bab6a308-d9a1-4264-aa48-71688dc9c342" />

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects)

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by NueloSE** [comment]
May I take this issue on?

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by Luluameh** [comment]
Could I try solving this?

**Comment by Joe-joe25** [comment]
I’m interested in this one and really love to work on it contributing to this community

**Comment by FrankiePower** [comment]
I am a frontend developer with over 3 years of experience, and I have recently graduated from Web3Bridge Africa, the premier and largest blockchain developer community in Africa. I am well-equipped to build the post component with a focus on both functionality and accessibility.This project will take me approximately one day to complete, ensuring that all accessibility features are thoroughly implemented.

**Comment by 3th-Enjay** [comment]
Would love to tackle this!

**Comment by kayceeDev** [comment]
Can I contribute to this one?

**Comment by derianrddev** [comment]
**Hello SocialSphere team,**

I’m **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your Stellar-based project during the **Only Dust 11** hackathon 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to resolve the *issue*

1. Design a functional React component that includes:
    - The **Post Profile** component.
    - The post title or question.
    - The post category.
    - The number of votes.
2. Use the provided color palette to ensure visual consistency.
3. Ensure the component is fully responsive for proper visualization across different devices.
4. Validate the final design using the provided image as a reference.
5. Test the component to ensure the parameters (question, category, and votes) render correctly.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by akintewe** [comment]
Hi, I'm interested in taking on the this task. I am a frontend/ UIUX developer and i have experience in working with detailed designs. I've reviewed the requirements and I'm confident I can deliver. I'd love to discuss further and get started. Looking forward to hearing from you. ETA 12hours :)

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
Can I handle this task?

**Comment by diegoTech14** [comment]
Hello @bitfalt  my name is Diego Duarte Fernández, I'm a software engineer from Costa Rica and Dojo Coding member ⛩️, I have experience with technologies like JavaScript, Nextjs, TypeScript. I really like the web design so I think that my experience could match with this issue perfectly also I'm maintainer of SafeTrust project which is a security deposit service project. 🤖

I would love to tackle this issue and contribute for your amazing project.

#### Step by step for this issue:

1. Design a scalable component to ensure the great integration and atomicity functionality, this will include the following characteristics:
    * Profile and its role
    * The post category (Art or anything)
    * Label post
    * Input field for the post

2. Following the color pallete to ensure that matches with the web design

3. Ensure that the component is fully responsive for a great user experience

4. Validating the design using the photo provided and testing the component to ensure that everything is rendering correctly.

Thanks for your consideration.

Best regards, 

Diego Duarte Fernández. ✨

**Comment by mimisavage** [comment]
I’m interested in this one.

**Comment by No-bodyq** [comment]
I'd be happy to do this.

**Comment by Villarley** [comment]
Hi👋🏻
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
To tackle this issue:
I’ll create a Post component that includes the Post Profile component, displays the question, category, and amount of votes, and uses the provided color palette for accurate styling. The component will accept question, category, and amount of votes as props.

ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by morelucks** [comment]
Hi, My name is Kamshak Lucky Isuwa, and I am excited to apply for the frontend developer role to create the Post component. With experience in React.js, Next.js, JavaScript, and UI/UX best practices, I am confident in delivering a visually appealing and fully functional component within 24 hours, adhering to the provided design and color palette.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue and my ETA is 2 days

**Comment by Emmanex01** [comment]
I'm Emmanuel Tochukwu, 
A Frontend developer, proficient in Reactjs, tailwindcss, typescript, Cairo Programming Languages.
May I be assigned to this?

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 KindFi and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #11! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 hacks.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

* GitHub: https://github.com/Bran18?tab=repositories
* OnlyDust: https://app.onlydust.com/u/Bran18
* X https://x.com/branfdez_18
* LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by SudiptaPaul-31** [comment]
I'd love to work on this!

**Comment by khayss** [comment]
I'd like to handle this task.

I'm a full-stack developer. I can build production grade frontend applications, therefore, I can comfortably work on this issue.

Having read the issue description and gotten a proper understanding of what the final component should be, I can implement this component without any difficulty, making sure it meets all the necessary specifications.

**Comment by Dorcas18** [comment]
Can I work on this, please?

**Comment by Nityam573** [comment]
Could I take a shot at this?

**Comment by diegoTech14** [comment]
@bitfalt thanks for the opportunity, I will start ASAP!
